
[info]
author = "陈与义"
deck = "New::语文::挖空"
card_template = "语文::古诗文::挖空"
mode = "poem"
title = "临江仙·夜登小阁，忆洛中旧游"

[content]
paragraph = [
    "忆昔午桥桥上饮，坐中多是豪英。长沟流月去无声。杏花疏影里，吹笛到天明。",
    "二十余年如一梦，此身虽在堪惊。闲登小阁看新晴。古今多少事，渔唱起三更。",
]
