[info]
deck = "古诗文挖空"
notetype = "语文::古诗文::挖空"
mode = "poem"
title = "十五从军征"

[content]
paragraph = [
    "十五从军征，八十始得归。道逢乡里人：「家中有阿谁？」「遥看是君家，松柏冢累累。」兔从狗窦入，雉从梁上飞。中庭生旅谷，井上生旅葵。舂谷持作饭，采葵持作羹。羹饭一时熟，不知饴阿谁。出门东向看，泪落沾我衣。",
]
