[info]
author = "辛弃疾"
deck = "New::语文::挖空"
notetype = "语文::古诗文::挖空"
mode = "poem"
title = "南乡子・登京口北固亭有怀"

[content]
paragraph = [
    "何处望神州？满眼风光北固楼。千古兴亡多少事？悠悠。不尽长江滚滚流。",
    "年少万兜鍪，坐断东南战未休，天下英雄谁敌手？曹刘。生子当如孙仲谋。",
]
