[info]
author = "辛弃疾"
deck = "New::语文::挖空"
notetype = "语文::古诗文::挖空"
mode = "poem"
title = "太常引·建康中秋夜为吕叔潜赋"

[content]
paragraph = [
    "一轮秋影转金波，飞镜又重磨。把酒问姮娥：被白发，欺人奈何？",
    "乘风好去，长空万里，直下看山河。斫去桂婆娑，人道是，清光更多。"
]
