
[info]
author = "张养浩"
deck = "New::语文::挖空"
card_template = "语文::古诗文::挖空"
mode = "poem"
title = "山坡羊 · 骊山怀古"

[content]
paragraph = ["骊山四顾，阿房一炬，当时奢侈今何处？只见草萧疏，水萦纡。", "至今遗恨迷烟树。列国周齐秦汉楚。赢，都变做了土；输，都变做了土。"]
