[info]
author = "张孝祥"
deck = "New::语文::挖空"
notetype = "语文::古诗文::挖空"
mode = "poem"
title = "念奴娇・过洞庭"

[content]
paragraph = [
    "洞庭青草，近中秋，更无一点风色。玉鉴琼田三万顷，着我扁舟一叶。素月分辉，明河共影，表里俱澄澈。悠然心会，妙处难与君说。",
    "应念岭海经年，孤光自照，肝肺皆冰雪。短发萧骚襟袖冷，稳泛沧浪空阔。尽挹西江，细斟北斗，万象为宾客。扣舷独啸，不知今夕何夕！",
]
