[info]
author = "《诗经·秦风》"
card_template = "语文::古诗文::挖空"
mode = "poem"
deck = "New::语文::挖空"
title = "无衣"

[content]
paragraph = [
    "岂曰无衣？与子同袍。王于兴师，修我戈矛，与子同仇。岂曰无衣？与子同泽。王于兴师，修我矛戟，与子偕作。岂曰无衣？与子同裳。王于兴师，修我甲兵，与子偕行。",
]
