[info]
author = "王磐"
notetype = "语文::古诗文::挖空"
mode = "poem"
deck = "古诗文填空"
dynasty = "明"
title = "朝天子・咏喇叭"

[content]
paragraph = [
    "喇叭，唢呐，曲儿小腔儿大。官船来往乱如麻，全仗你抬声价。军听了军愁，民听了民怕。哪里去辨甚么真共假？眼见的吹翻了这家，吹伤了那家，只吹的水尽鹅飞罢！",
]
