[info]
author = "范仲淹"
deck = "New::语文::挖空"
card_template = "语文::古诗文::挖空"
mode = "poem"
title = "渔家傲 · 秋思"
[content]

paragraph = [
    "塞下秋来风景异，衡阳雁去无留意。四面边声连角起，千嶂里，长烟落日孤城闭。",
    "浊酒一杯家万里，燕然未勒归无计，羌管悠悠霜满地。人不寐，将军白发征夫泪。",
]
