
[info]
author = "秋瑾"
deck = "New::语文::挖空"
card_template = "语文::古诗文::挖空"
mode = "poem"
title = "满江红"

[content]
paragraph = [
    "小住京华，早又是中秋佳节。为篱下黄花开遍，秋容如拭。四面歌残终破楚，八年风味徒思浙。苦将侬强派作蛾眉，殊未屑！",
    "身不得，男儿列，心却比，男儿烈。算平生肝胆，因人常热。俗子胸襟谁识我？英雄末路当磨折。莽红尘何处觅知音？青衫湿！",
]
