
[info]
author = "辛弃疾"
deck = "New::语文::挖空"
card_template = "语文::古诗文::挖空"
mode = "poem"
title = "破阵子 · 为陈同甫赋壮词以寄之"
[content]

paragraph = [
    "醉里挑灯看剑，梦回吹角连营。八百里分麾下炙，五十弦翻塞外声，沙场秋点兵。",
    "马作的卢飞快，弓如霹雳弦惊。了却君王天下事，赢得生前身后名。可怜白发生！",
]
