[info]
author = "辛弃疾"
notetype = "语文::古诗文::挖空"
mode = "poem"
deck = "New::语文::挖空"
dynasty = "宋"
title = "菩萨蛮·书江西造口壁"

[content]
paragraph = [
    "郁孤台下清江水，中间多少行人泪。西北望长安，可怜无数山。",
    "青山遮不住，毕竟东流去。江晚正愁余，山深闻鹧鸪。"
]
